#!c:\users\marin343\documents\github\siop-2023-360-misalignment\econml_env\scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
